# Add credentials for Bitbucket for later use in jobs
- name: Copy xml file for creating Bitbucket credentials
  template:
    src: credentials-username-password.xml
    dest: "{{ temp_dir }}/credentials-bitbucket.xml"
    owner: jenkins
    group: jenkins
  vars:
    credentials_id: "{{ jenkins_bitbucket_credentials_id }}"
    credentials_username: "{{ jenkins_bitbucket_ci_account }}"
    credentials_password: "{{ jenkins_bitbucket_ci_password }}"


- name: Add Bitbucket credentials
  shell: "cat {{ temp_dir }}/credentials-bitbucket.xml | {{ jenkins_cli_command }} create-credentials-by-xml system::system::jenkins _"
  become: true
  become_user: jenkins
  register: shell_jenkins_cli_bitbucket_credentials
  failed_when: shell_jenkins_cli_bitbucket_credentials.rc > 1
  changed_when: "(shell_jenkins_cli_bitbucket_credentials | success) and 'Changed' not in shell_jenkins_cli_bitbucket_credentials.stdout"
