- name: Add jenkins user into docker group
  user:
    name: jenkins
    groups: docker
    append: yes
  notify:
    - "restart docker"
    - "Restart Service 'jenkins'"

# force restart now
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers